name: Build PrefixHQ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 requests pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed PrefixHQ.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PrefixHQ
          path: dist/
